name: Tests

on:
  pull_request:
    branches: [ main ] # pull on main

jobs:
  run_style_check: # STYLE CHECK
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          activate-environment: ULF_waves
          environment-file: env.yml
      - run: pycodestyle --exclude=src/radiation_belt_analysis_v4.py,test/unit/test_mfa_transform.py $(git ls-files "*.py")

  run_unit_tests: # UNIT TESTS
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          activate-environment: ULF_waves
          environment-file: env.yml
      - name: Run PLOTTING tests
        run: |
          cd test/unit
          python -m unittest test_plots.py
      - name: Run DATA PREP tests
        run: |
          cd test/unit
          python -m unittest test_data_prep.py
      - name: Run CALCULATING TAU tests
        run: |
          cd test/unit
          python -m unittest test_calc_tau.py
      - name: Run CALLING TAU tests
        run: |
          cd test/unit
          python -m unittest test_call_tau.py
      - name: Run MFA TRANSFORM tests
        run: |
          cd test/unit
          python -m unittest test_mfa_transform.py
      - name: Run UTILS tests
        run: |
          cd test/unit
          python -m unittest test_utils.py

  run_func_tests: # FUNCTIONAL TESTS
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v2
      - uses: mamba-org/setup-micromamba@v1
        with:
          activate-environment: ULF_waves
          environment-file: env.yml
      - run: |
          cd test/functional
          bash func_tests.sh